version: '3.8'
services:

  osc-dm-marketplace-ux:
    image: ${DOCKERHUB_USERNAME}/osc-dm-marketplace-ux:latest
    # hostname: osc-dm-marketplace-ux
    # container_name: osc-dm-marketplace-ux
    ports:
    # OUTSIDE:INSIDE
    # curl http://localhost:${SERVER_PORT}/data
    - 3000:3000
    # volumes:
    # - ${PROJECT_DIR}/config:/app/config
    # - ${PROJECT_DIR}/data:/app/data
    environment:
    - REACT_APP_SERVER_URL=${REACT_APP_SERVER_URL}

    networks:
    - localnet

networks:
  localnet:
    external: true